### ISSUE TITLE
Helm Push Fails

### ISSUE THREAD

**Issue by or4dx** [appany/helm-oci-chart-releaser#11]
**Describe the bug**
Helm Push Fails as it seems to break the helm push command

**To Reproduce**

```   - name: Chart | Push
        uses: appany/helm-oci-chart-releaser@v0.4.1
        with:
          name: ${{ matrix.chartname }}
          repository: ${{ matrix.chartrepo }}
          tag: |
            ${{ matrix.chartversion }}
          path: ${{ matrix.chartpath }} # Default charts/{name}
          registry: quay.io
          registry_username: ${{ env.QUAY_USER }}
          registry_password: ${{ secrets.QUAY_TOKEN }}
          update_dependencies: "true" # Defaults to false
```

**Expected behavior**
It should run the full command like

`  helm push kafka-0.2.0.tgz oci://quay.io/kafka-chart`

**Screenshots**

Helm Push Fails as it seems to break the helm push command as shown below.

<img width="546" alt="Screenshot 2023-09-20 at 2 04 03 PM" src="https://github.com/appany/helm-oci-chart-releaser/assets/19908496/1171d14f-fdce-442e-9fa6-0a99f3d262c5">

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: chrome
 - Version: Version 117.0.5938.88

**Comment by sergeyshaykhullin** [comment]
@or4dx Please, check your input values

https://github.com/appany/helm-oci-chart-releaser/blob/240cda338baff2e248fa235b7e7dade7bf658cd3/action.yaml#L61

You have to delete start new line and use yaml strip new lines |-, or single line string without new lines
https://yaml-multiline.info/

For example
```yaml
uses: appany/helm-oci-chart-releaser@v0.4.1
with:
  name: ${{ matrix.chartname }}
  repository: ${{ matrix.chartrepo }}
  tag: ${{ matrix.chartversion }}
  path: ${{ matrix.chartpath }} # Default charts/{name}
  registry: quay.io
  registry_username: ${{ env.QUAY_USER }}
  registry_password: ${{ secrets.QUAY_TOKEN }}
  update_dependencies: "true" # Defaults to false
```
