### ISSUE TITLE
appany/helm-oci-chart-releaser:0.4.0 Helm Push is broken (+ incorrect status) on ubuntu-20.04

### ISSUE THREAD

**Issue by rowi1de** [appany/helm-oci-chart-releaser#7]
**Describe the bug**
- Helm Push is broken: The Helm Package is saving to wrong location or file
- Even the package wasn't pushed, the workflow reported success

**To Reproduce**
- The Workflow stopped working without changing the version
- Version: appany/helm-oci-chart-releaser@v0.4.0
```yaml
jobs:
  helm-publish-and-release-charts:
   # if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest 
	- name: Push helm-app chart
	        uses: appany/helm-oci-chart-releaser@v0.4.0
	        with:
	          repository: some-service
	          registry: ghcr.io/${{ github.repository_owner }}
	          registry_username: __token__
	          registry_password: ${{ secrets.GITHUB_TOKEN }}
	          name: service-app
	          path: k8s/helm-app
	          tag: 1.2.3
```

From the logs you see that the helm push is not finding the output:
```shell
Run echo *** | helm registry login -u __token__ --password-stdin ghcr.io/xxx
Login succeeded
  helm package k8s/helm-app --version 0.0.123
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    HELM_EXPERIMENTAL_OCI: 1
Successfully packaged chart and saved it to: 
```
`saved it to: ` is literally empty 

The following helm push is assuming the previous step was successful:
```shell
  helm push service-app-0.0.123.tgz oci://ghcr.io/xxx/yyy
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    HELM_EXPERIMENTAL_OCI: 1
The Kubernetes package manager

To begin working with Helm, run the 'helm init' command:

	$ helm init

This will set up any necessary local configuration.
```
It will just print the helm help, because the packaged file could not be found

**Comment by sergeyshaykhullin** [comment]
I can't reproduce this on v0.4.0, does your directory `k8s/helm-app` contains `service-app`?

```yaml
  - name: Chart
    uses: appany/helm-oci-chart-releaser@v0.4.0
    with:
      name: ${{ ... }}
      repository: ${{ ... }}
      tag: ${{ steps.release.outputs.tag }}
      path: src
      registry: ${{ ... }}
      registry_username: ${{ ... }}
      registry_password: ${{ ... }}
```

![image](https://user-images.githubusercontent.com/46970457/201706708-535ade8f-34de-4c6d-a343-ebe989975b9c.png)
![image](https://user-images.githubusercontent.com/46970457/201706798-37329382-6588-41db-8191-b798f0184ecd.png)
